# Generated by Django 4.0.6 on 2022-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0002_addmobile_price_addmobile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmobile',
            name='salesPackage',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='backImage',
            field=models.ImageField(upload_to='', verbose_name='addMobiles/'),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='frontImage',
            field=models.ImageField(upload_to='', verbose_name='addMobiles/'),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='leftImage',
            field=models.ImageField(upload_to='', verbose_name='addMobiles/'),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='rightImage',
            field=models.ImageField(upload_to='', verbose_name='addMobiles/'),
        ),
    ]
