# Generated by Django 4.0.6 on 2022-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0003_addmobile_salespackage_alter_addmobile_backimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmobile',
            name='backImage',
            field=models.ImageField(upload_to='addMobiles/'),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='frontImage',
            field=models.ImageField(upload_to='addMobiles/'),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='leftImage',
            field=models.ImageField(upload_to='addMobiles/'),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='rightImage',
            field=models.ImageField(upload_to='addMobiles/'),
        ),
    ]
