# Generated by Django 4.0.6 on 2022-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0004_alter_addmobile_backimage_alter_addmobile_frontimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmobile',
            name='battery',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmobile',
            name='camera',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmobile',
            name='internalStorage',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmobile',
            name='ram',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
