# Generated by Django 4.0.6 on 2022-12-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0005_addmobile_battery_addmobile_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('lap_type', models.CharField(max_length=100)),
                ('suitable', models.CharField(max_length=100)),
                ('Battery_cell', models.CharField(max_length=100)),
                ('ms_office', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('dgm', models.CharField(max_length=100)),
                ('dgmc', models.CharField(max_length=100)),
                ('processor_brand', models.CharField(max_length=100)),
                ('processor_name', models.CharField(max_length=100)),
                ('ssd', models.CharField(max_length=100)),
                ('ssd_capacity', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('ram_type', models.CharField(max_length=100)),
                ('processor_varient', models.CharField(max_length=100)),
                ('clock_speed', models.CharField(max_length=100)),
                ('graphic_processor', models.CharField(max_length=100)),
                ('os_architecture', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('touch_screen', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('screen_resolution', models.CharField(max_length=100)),
                ('screen_type', models.CharField(max_length=100)),
                ('Speakers', models.CharField(max_length=100)),
                ('internal_mic', models.CharField(max_length=100)),
                ('Sound_properties', models.CharField(max_length=100)),
                ('refresh_rate', models.CharField(max_length=100)),
                ('wireless_lan', models.CharField(max_length=100)),
                ('bluetooth', models.CharField(max_length=100)),
                ('ethernet', models.CharField(max_length=100)),
                ('warranty_type', models.CharField(max_length=100)),
                ('warranty_service_type', models.CharField(max_length=100)),
                ('covered_in_warranty', models.CharField(max_length=100)),
                ('not_in_warranty', models.CharField(max_length=100)),
                ('frontImage', models.ImageField(upload_to='', verbose_name='addLap/')),
                ('backImage', models.ImageField(upload_to='', verbose_name='addLap/')),
                ('leftImage', models.ImageField(upload_to='', verbose_name='addLap/')),
                ('rightImage', models.ImageField(upload_to='', verbose_name='addLap/')),
            ],
        ),
    ]
