# Generated by Django 4.0.6 on 2022-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0007_addlap_price_addlap_description_addlap_marketprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlap',
            name='brand_name',
            field=models.CharField(default='scsc', max_length=100),
            preserve_default=False,
        ),
    ]
