# Generated by Django 4.0.6 on 2022-12-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0008_addlap_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('speaker_type', models.CharField(max_length=100)),
                ('bluetooth', models.CharField(max_length=100)),
                ('configuration', models.CharField(max_length=100)),
                ('power_output', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('battery_capacity', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('market_price', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('frontImage', models.ImageField(upload_to='', verbose_name='addspeaker/')),
                ('backImage', models.ImageField(upload_to='', verbose_name='addspeaker/')),
            ],
        ),
    ]
