# Generated by Django 4.0.6 on 2022-12-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0009_addspeaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addspeaker',
            old_name='backImage',
            new_name='Image1',
        ),
        migrations.RenameField(
            model_name='addspeaker',
            old_name='frontImage',
            new_name='Image2',
        ),
    ]
