# Generated by Django 4.0.6 on 2022-12-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0010_rename_backimage_addspeaker_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addspeaker',
            old_name='Image2',
            new_name='Image',
        ),
    ]
