# Generated by Django 4.0.6 on 2022-12-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0011_rename_image2_addspeaker_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addspeaker',
            old_name='Image',
            new_name='Image2',
        ),
    ]
