# Generated by Django 4.0.6 on 2022-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0012_rename_image_addspeaker_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddHf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('hf_type', models.CharField(max_length=100)),
                ('inline_remote', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('hf_design', models.CharField(max_length=100)),
                ('deep_bass', models.CharField(max_length=100)),
                ('microphone', models.CharField(max_length=100)),
                ('warranty_summary', models.CharField(max_length=100)),
                ('covered_warranty', models.CharField(max_length=100)),
                ('not_in_warranty', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name='addhf/')),
                ('image2', models.ImageField(upload_to='', verbose_name='addhf/')),
                ('market_price', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
