# Generated by Django 4.0.6 on 2022-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0013_addhf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cable_type', models.CharField(max_length=100)),
                ('connector1', models.CharField(max_length=100)),
                ('connector2', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('meterial', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('covered_warranty', models.CharField(max_length=100)),
                ('not_in_warranty', models.CharField(max_length=100)),
                ('market_price', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name='addCable/')),
                ('image2', models.ImageField(upload_to='', verbose_name='addCable/')),
            ],
        ),
        migrations.AlterField(
            model_name='addhf',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='addCable/'),
        ),
        migrations.AlterField(
            model_name='addhf',
            name='image2',
            field=models.ImageField(upload_to='', verbose_name='addCable/'),
        ),
    ]
