# Generated by Django 4.0.6 on 2022-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0014_addcable_alter_addhf_image1_alter_addhf_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhf',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='addhf/'),
        ),
        migrations.AlterField(
            model_name='addhf',
            name='image2',
            field=models.ImageField(upload_to='', verbose_name='addhf/'),
        ),
    ]
