# Generated by Django 4.0.6 on 2022-12-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0015_alter_addhf_image1_alter_addhf_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('output_interferance', models.CharField(max_length=100)),
                ('led', models.CharField(max_length=100)),
                ('dispaly', models.CharField(max_length=100)),
                ('cable_length', models.CharField(max_length=100)),
                ('power_input', models.CharField(max_length=100)),
                ('power_source', models.CharField(max_length=100)),
                ('output_current', models.CharField(max_length=100)),
                ('output_wattage', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('covered_warranty', models.CharField(max_length=100)),
                ('not_in_warranty', models.CharField(max_length=100)),
                ('market_price', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name='addCharger/')),
                ('image2', models.ImageField(upload_to='', verbose_name='addCharger/')),
            ],
        ),
    ]
