# Generated by Django 4.0.6 on 2022-12-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0016_addcharger'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMmc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('write_speed', models.CharField(max_length=100)),
                ('read_speed', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('covered_warranty', models.CharField(max_length=100)),
                ('not_in_warranty', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('market_price', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name='addMmc/')),
                ('image2', models.ImageField(upload_to='', verbose_name='addMmc/')),
            ],
        ),
    ]
