# Generated by Django 4.0.6 on 2022-12-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0017_addmmc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPowerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('sales_package', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('suitable_device', models.BigIntegerField()),
                ('nof_output_ports', models.BigIntegerField()),
                ('warranty', models.CharField(max_length=100)),
                ('covered_warranty', models.CharField(max_length=100)),
                ('not_in_warranty', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('market_price', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='', verbose_name='addPowerbank/')),
                ('image2', models.ImageField(upload_to='', verbose_name='addPowerbank/')),
            ],
        ),
    ]
