# Generated by Django 4.0.6 on 2022-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0018_addpowerbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpowerbank',
            name='suitable_device',
            field=models.CharField(max_length=100),
        ),
    ]
