# Generated by Django 4.0.6 on 2022-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0019_alter_addpowerbank_suitable_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlap',
            name='processor_generation',
            field=models.CharField(default='ascsc', max_length=100),
            preserve_default=False,
        ),
    ]
