# Generated by Django 4.0.6 on 2022-10-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopAdminLogin',
        ),
    ]
