# Generated by Django 4.0.6 on 2022-10-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('cpswd', models.CharField(max_length=100)),
            ],
        ),
    ]
