# Generated by Django 4.0.6 on 2022-10-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_customersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersignup',
            name='cpswd',
        ),
    ]
