# Generated by Django 4.0.6 on 2022-12-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_customersignup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersignup',
            name='phone',
        ),
    ]
