# Generated by Django 4.0.6 on 2022-12-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_customersignup_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSignup',
        ),
    ]
