# Generated by Django 4.0.6 on 2022-12-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_delete_customersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
